### ISSUE TITLE
Use existing map as template

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/db-roadmap#21]
#### Summary
DistrictBuilder allows users to create maps from a blank template, which means they must draw every map from scratch. Sometimes, however, mappers may not want to start from scratch but rather start using an existing map as a template. This can is useful if they are just starting out to get a feel for a district map, or if they want to take an existing map and make their own edits to it. Further, we want to support the ability for mappers to evaluate map proposals they see and suggest changes, and this feature is the prerequisite to that.

#### Intended Outcome
Enable users to start drawing/editing a map using an existing map as a starting point.

#### How will it work?
A user will be able to choose an existing plan to use as a template to start drawing from. Starting from a template will create a copy of the original plan and the new plan will belong to the user. All the existing district boundaries will remain, and the rules that governed the original plan will govern the new plan.

--------
⬇️ Please click the 👍 reaction if you want to see this feature happen!

**Comment by LevHirschhorn** [comment]
Just discovered this tool and this was the first thing I came looking for! I would really love to be able to experiment with the Pennsylvania State House maps using the current district lines. It would be quite a hassle to have to recreate them from scratch!

**Comment by wesg52** [comment]
I am not sure if this is in scope for this feature, but at fairmandering.org we algorithmically create quadrillions of maps (implicitly, paper forthcoming), so it would be great to have a way to upload an arbitrary plan encoded as {FIPS code : district} rather than just a few templates.
