### ISSUE TITLE
Add West Virginia data (2010 Census)

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/db-roadmap#42]
#### Summary
We will add 2010 census data for the state of West Virginia.

#### Intended Outcome
West Virginia data (geography, demographics, chambers) is available for mappers to use in DistrictBuilder.

#### How will it work?
Mappers will be able to select West Virginia from states available to map.

--------
⬇️ Please click the 👍 reaction if you want to see this feature happen!

**Comment by fspc** [comment]
Woohoo, thank-you for this!
