### ISSUE TITLE
Add Maryland data (2010 Census)

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/db-roadmap#54]
#### Summary
We will add 2010 census data for the state of Maryland.

#### Intended Outcome
Maryland data (geography, demographics, chambers) is available for mappers to use in DistrictBuilder.

#### How will it work?
Mappers will be able to select Maryland from states available to map.

--------
⬇️ Please click the 👍 reaction if you want to see this feature happen!

**Comment by ryangniadek** [comment]
What format is the data needed in? Is it just precinct level or census-block level GeoJSON data? I could potentially help source that.

**Comment by MarcusAlzona** [comment]
Like @ryangniadek I am also interested in working with Maryland data, state and some county data.  What can I do to help @tgilcrest?

**Comment by MarcusAlzona** [comment]
AFAIK this corresponds to https://github.com/PublicMapping/districtbuilder/issues/511
