### ISSUE TITLE
Add Tennessee data (2010 Census)

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/db-roadmap#56]
#### Summary
We will add 2010 census data for the state of Tennessee.

#### Intended Outcome
Tennessee data (geography, demographics, chambers) is available for mappers to use in DistrictBuilder.

#### How will it work?
Mappers will be able to select Tennessee from states available to map.

--------
⬇️ Please click the 👍 reaction if you want to see this feature happen!

**Comment by coolhannes** [comment]
@tgilcrest Let me know if I can help!
